# user/config/groups.yaml

visitors:
  groupname: visitors
  description: "Bejelentkezett látogatók, kommentezhetnek"
  readableName: "Látogatók"
  access:
    site:
      login: true
    comments:
      create: true
      
editors:
  groupname: editors
  description: "Szerkesztők, saját cikkeket kezelhetnek"
  readableName: "Szerkesztők"
  access:
    site:
      login: true
    admin:
      login: true
      pages: true
    pages:
      create: true
      read: true
      update: true
      delete: true
    comments:
      create: true
      moderate: true

administrators:
  groupname: administrators
  description: "Teljes körű adminisztrátori jogosultságok"
  readableName: "Adminisztrátorok"
  access:
    admin:
      super: true
    site:
      login: true