visitors:
  icon: users
  readableName: 'Guest Users'
  access:
    site:
      login: false
  
administrators:
  groupname: administrators
  readableName: 'Blog Administrators'
  icon: fa-users
  access:
    admin:
      login: true
      super: true
    site:
      login: true