# user/config/groups.yaml - Frissített 5 szintű rendszer

visitors:
  groupname: visitors
  description: "Bejelentkezett látogatók, kommentezhetnek"
  readableName: "Látogatók"
  access:
    site:
      login: true
    comments:
      create: true

moderators:
  groupname: moderators
  description: "Közösségi moderátorok, kommenteket és felhasználókat kezelhetnek"
  readableName: "Moderátorok"
  access:
    site:
      login: true
    comments:
      create: true
      moderate: true        # Kommentek moderálása
      delete: true          # Kommentek törlése
      approve: true         # Kommentek jóváhagyása
    users:
      moderate: true        # Felhasználók moderálása (figyelmeztetés, ideiglenes tiltás)
    reports:
      view: true            # Jelentések megtekintése
      handle: true          # Jelentések kezelése

editors:
  groupname: editors
  description: "Tartalom szerkesztők, cikkeket és oldalakat kezelhetnek"
  readableName: "Szerkesztők"
  access:
    site:
      login: true
    admin:
      login: true           # Admin panel hozzáférés
      pages: true           # Oldalak kezelése
    pages:
      create: true          # Új cikkek/oldalak létrehozása
      read: true            # Oldalak olvasása
      update: true          # Saját és mások cikkeinek szerkesztése
      delete: true          # Cikkek törlése
      publish: true         # Cikkek publikálása
    media:
      create: true          # Képek/fájlok feltöltése
      delete: true          # Média fájlok törlése
    comments:
      create: true          # Kommentálás
    categories:
      manage: true          # Kategóriák kezelése
    tags:
      manage: true          # Címkék kezelése

administrators:
  groupname: administrators
  description: "Teljes körű adminisztrátori jogosultságok"
  readableName: "Adminisztrátorok"
  access:
    admin:
      super: true           # Minden admin jogosultság
    site:
      login: true
