absolute_urls: false

home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: true

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_module_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true

gpm:
  verify_peer: true

languages:
  supported:
    - en        # English (default)
    - hu        # Hungarian 
  default_lang: en
  include_default_lang: false      # ommit /en prefix for default language
  include_default_lang_file_extension: true
  http_accept_language: true       # automatic selection based on the browser language
  session_store_active: true       # Language selection stored in session
  content_fallback:
    hu: ['hu', 'en']              # Hungarian → English fallback
    en: ['en', 'hu']              # English → Hungarian fallback
  translations: true
  translations_fallback: true
  override_locale: true            # Setting PHP locale according to the active language

home:
  aliases:
    hu: /fooldal                   # Hungarian path for home page
    en: /homepage                  # English path for home page